# Generated by Django 5.2.2 on 2025-06-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='time_multipliers',
            field=models.JSONField(default=list),
        ),
    ]
