# Generated by Django 5.2.2 on 2025-06-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricingconfig_time_multipliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='time_multipliers',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_additional_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_base_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_charge_per_unit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_free_minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_unit_minutes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TimeMultiplierTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_minutes', models.IntegerField()),
                ('multiplier', models.FloatField()),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing.pricingconfig')),
            ],
        ),
        migrations.DeleteModel(
            name='PricingConfigLog',
        ),
    ]
