# Generated by Django 5.2.2 on 2025-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_pricingconfig_time_multipliers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
