# Generated by Django 5.2.2 on 2025-06-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_pricingconfig_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemultipliertier',
            name='min_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timemultipliertier',
            name='pricing_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='pricing.pricingconfig'),
        ),
    ]
